GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Hello router middleware",
    "author": "RayC",
    "url": "",
    "likes": 1919810
}

### 
# unknown endpoint
GET http://localhost:3003/api/blogo

###
# get by id
GET http://localhost:3003/api/blogs/6419cfb49e9d16b32ccb27a7

###