GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Hello World",
    "author": "RayC",
    "url": "",
    "likes": 1919810
}

### 
# unknown endpoint
GET http://localhost:3003/api/blogo

###