delete http://localhost:3001/api/persons/2

### 

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ray",
    "number" : "1234567890"
}

###

GET http://localhost:3001/api/persons