delete http://localhost:3001/api/persons/640ad7589a28f363fb0c268b

### 

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jefery",
    "number" : "9996699"
}

###

GET http://localhost:3001/api/persons