GET http://localhost:3001/api/notes

### 

DELETE http://localhost:3001/api/notes/2

###

# valid get by id
get http://localhost:3001/api/notes/640c7e921379d545129e1b2a

### 

# invalid get by id (404 not found)
get http://localhost:3001/api/notes/5c41c90e84d891c15dfa3431

### 

# invalid get by id (invalid id, 400 bad request)
get http://localhost:3001/api/notes/5c41c90e8_d891c1-dfa3431

### 

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content" : "a mongoose posted note",
    "important" : true
}

### 
HEAD http://localhost:3001/api/notes

### 
PUT http://localhost:3001/api/notes/640c7ef81379d545129e1b2f
Content-Type: application/json

{
    "content" : "Modifying a mongoose posted note via PUT",
    "important" : true
}